spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000

  config:
    activate:
      on-profile: local
    import:
      application-secret.yml
logging:
  config:
    classpath:logback-spring.xml
  level:
    org.hibernate.SQL: debug

image:
  path: test-image/